import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#ebdcff",
        "tertiary-fixed-dim": "#e9c400",
        "error-container": "#93000a",
        "surface-container-highest": "#3a2f4e",
        "on-primary-container": "#554300",
        "surface-container-lowest": "#130825",
        "on-surface-variant": "#d0c5af",
        "tertiary": "#f2cc00",
        "surface-variant": "#3a2f4e",
        "on-tertiary": "#3a3000",
        "outline": "#99907c",
        "on-background": "#ebdcff",
        "surface-dim": "#180e2a",
        "on-tertiary-container": "#534400",
        "primary": "#f2ca50",
        "inverse-primary": "#735c00",
        "secondary": "#dbb8ff",
        "surface": "#180e2a",
        "on-secondary-fixed": "#2b0052",
        "primary-fixed-dim": "#e9c349",
        "surface-container-high": "#2f2542",
        "on-primary-fixed-variant": "#574500",
        "inverse-on-surface": "#362b49",
        "tertiary-fixed": "#ffe16d",
        "on-secondary": "#470083",
        "on-error": "#690005",
        "primary-container": "#d4af37",
        "tertiary-container": "#d2b100",
        "on-tertiary-fixed-variant": "#544600",
        "on-tertiary-fixed": "#221b00",
        "on-primary": "#3c2f00",
        "surface-container": "#251a37",
        "outline-variant": "#4d4635",
        "secondary-fixed": "#efdbff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#241a00",
        "secondary-container": "#6807ba",
        "on-secondary-fixed-variant": "#6600b7",
        "surface-bright": "#3f3452",
        "surface-container-low": "#201633",
        "on-secondary-container": "#d0a6ff",
        "on-surface": "#ebdcff",
        "secondary-fixed-dim": "#dbb8ff",
        "surface-tint": "#e9c349",
        "error": "#ffb4ab",
        "primary-fixed": "#ffe088",
        "background": "#180e2a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-4xl": "6rem",
        "space-2xs": "0.25rem",
        "margin-tablet": "2.5rem",
        "gutter-tablet": "1.5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem",
        "margin-desktop": "4rem",
        "gutter-mobile": "1rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-desktop": "2rem",
        "margin-mobile": "1.25rem",
        "space-3xl": "4.5rem"
      },
      fontFamily: {
        "headline-sm": ["var(--font-syne)"],
        "title-lg": ["var(--font-plus-jakarta)"],
        "headline-lg-mobile": ["var(--font-syne)"],
        "body-lg": ["var(--font-plus-jakarta)"],
        "label-md": ["var(--font-space-grotesk)"],
        "label-caps": ["var(--font-space-grotesk)"],
        "headline-lg": ["var(--font-syne)"],
        "body-sm": ["var(--font-plus-jakarta)"],
        "display-hero": ["var(--font-syne)"],
        "display-hero-mobile": ["var(--font-syne)"],
        "body-md": ["var(--font-plus-jakarta)"],
        "headline-md": ["var(--font-syne)"]
      },
      fontSize: {
        "headline-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-hero": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "display-hero-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  }
};
export default config;
